version: '2'

services:
  phonebook-nginx:
    container_name: phonebook-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    depends_on:
      - phonebook-app
    ports:
      - "80:80"

  phonebook-mysql:
    container_name: phonebook-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
#    ports:
#      - "8181:8181"
    restart: always
